version: "3.5"

services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api-container
    image: node:14
    working_dir: /clean-ts-course
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"    
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/clean-ts-course/dist/
      - ./package.json:/clean-ts-course/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo